name = "resign-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "a0ce05e1163dc5b1c2520a356c47b319"

[ai]
binding = "AI"

[vars]
FIREBASE_PROJECT_ID = "a920604a-labs"
ALLOWED_ORIGINS = "http://localhost:5173,https://a920604a-labs.pages.dev"
